WITH CTE AS(

SELECT 
TO_TIMESTAMP(STARTED_AT),
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,

{{DAY_TYPE('STARTED_AT')}} as DAY_TYPE,

{{get_season('STARTED_AT')}} as STATION_OF_YEAR,

{{function1('STARTED_AT')}} as TENSE_OF_YEAR

FROM {{ ref('stg_bike') }} 

)

SELECT 
* 
FROM CTE